# Generated by Django 5.2.8 on 2025-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_customuser_hashed_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hashed_password',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
