# Generated by Django 5.2.8 on 2025-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hashed_password',
            field=models.CharField(default='solomon@2025', max_length=128),
        ),
    ]
